More stuff

diff --git a/bin/pe-utils b/bin/pe-utils
--- a/bin/pe-utils
+++ b/bin/pe-utils
@@ -2,7 +2,9 @@
 
 set -e
 
-## HELPER FUNCTIONS
+## HELPER FUNCTIONS/CONSTANTS
+
+GITHUB_DIR="/Users/enis.inan/GitHub"
 
 SCRIPT="$0"
 
@@ -92,7 +94,56 @@ function create_file_on() {
   on_host "${host}" "echo \"${contents}\" > ${path}"
 }
 
+
+function make_host_json() {
+  local host_type="$1"
+
+  for host_engine in "vmpooler" "nspooler"; do
+    if [[ "${host_engine}" == "vmpooler" ]]; then
+      vm=`floaty get "${host_type}" --url 'https://vmpooler.delivery.puppetlabs.net/api/v1'`
+    else
+      vm=`floaty get "${host_type}" --service ns --url 'https://nspooler-service-prod-1.delivery.puppetlabs.net'`
+    fi
+    if [[ "$?" -ne 0 ]]; then
+      continue
+    fi
+    host_name=`echo "${vm}" | awk {'print $2'}`
+
+
+    echo "{\"hostname\":\"${host_name}\",\"type\":\"${host_type}\",\"engine\":\"${host_engine}\"}"
+    return 0
+  done
+
+  return 1
+}
+
 ## COMMANDS
+
+function get_vm() {
+  local template="$1"
+
+  local USAGE="get-vm <template>"
+  validate_args "${USAGE}" template
+
+  host_json=`make_host_json "${template}"`
+  if [[ "$?" -ne 0 ]]; then
+    echo ""
+    echo "ERROR: Could not get a VM for the template ${template}!"
+    exit 1
+  fi
+
+  echo "${host_json}" | jq -r ".hostname"
+}
+
+function ssh_dir() {
+  local host="$1"
+  local dir="$2"
+
+  local USAGE="ssh-dir <host> <dir>"
+  validate_args "${USAGE}" host dir
+
+  ssh -t -oStrictHostKeyChecking=no root@${host} "cd ${dir}; bash"
+}
 
 function van_build() {
   local project="$1"
@@ -278,6 +329,47 @@ function setup_agent() {
 
   echo ""
   log_info "AGENT-VM: ${agent_vm}"
+}
+
+# Quick way to iterate on stuff
+function cp_dev_environments() {
+  local host="$1"
+
+  # Copy our dev_environment repo to this machine
+  scp -r "${GITHUB_DIR}/dev_environments" "root@${host}:/root/"
+}
+
+# TODO: Add code to checkout agent branch too (possibly)
+# NOTE: Can get build script this way from checking log output. Reverse engineer it.
+function setup_pa_dev_machine() {
+  local vm_platform="$1"
+  local agent_platform="$2"
+  local agent_branch="$3"
+
+  local USAGE="setup-pa-dev-machine <vm_platform> <agent_platform> <agent_branch>"
+  validate_args "${USAGE}" vm_platform agent_platform agent_branch
+
+  build_vm=`get-vm ${vm_platform}`
+
+  pushd "${GITHUB_DIR}/puppet-agent"
+    git fetch upstream
+    git checkout "${agent_branch}"
+    git reset --hard "upstream/${agent_branch}"
+    van_build puppet-agent "${agent_platform}" BUILD_LOGS "${build_vm}" --remote-workdir "/root"
+  popd
+
+  # We want to trigger runs using puppet apply only.
+  on_host "${build_vm}" "puppet resource service puppet ensure=stopped"
+
+  # Set our GitHub API token
+  on_host "${build_vm}" "echo 'export GITHUB_API_TOKEN=${GITHUB_API_TOKEN}' >> ~/.bash_profile"
+
+  # Copy our dev_environment repo to this machine
+  cp_dev_environments "${build_vm}"
+
+  on_host "${build_vm}" "source ~/.bash_profile && puppet apply --modulepath=\"/root\" -e 'class { \"dev_environments::basic\": }'"
+
+  echo "BUILD VM: ${build_vm}"
 }
 
 function setup_master() {
